# Generated by Django 4.0 on 2025-12-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='approval_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
