# Generated by Django 4.0 on 2025-12-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_hospital_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
