# Generated by Django 4.0 on 2025-12-20 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0003_alter_sendrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='FROM_USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='TO_USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
