# Generated by Django 4.0 on 2025-12-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_chat_from_user_alter_chat_to_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
