# Generated by Django 4.0 on 2025-12-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userprofile_latitude_userprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningcamp',
            name='place',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
