# Generated by Django 6.0 on 2026-01-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_screeningcamp_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='approval_status',
        ),
    ]
