# Generated by Django 6.0 on 2026-03-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_hospital_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='specialization',
        ),
    ]
